### PR TITLE
chore: fixed all the minor Clippy rants

### PR DESCRIPTION
**Pull request by kirushik**
As a preparation for #12 being merged

### CODE REVIEW

**Comment by kirushik** [comment]
I still find https://github.com/Alzymologist/Kalatori-backend/blob/5ba7f4db5faad3baff183058eaf88ee6856a2c0b/src/database.rs#L316-L325 and https://github.com/Alzymologist/Kalatori-backend/blob/5ba7f4db5faad3baff183058eaf88ee6856a2c0b/src/rpc.rs#L466-L488 suspicious, and would've preferred this would be a more concise logic.

Consumer asked for `invoices()`? Give them an `Iterator` over all the properly parsed elements in the db.

**Comment by Slesarew** [comment]
we can merge #12 first to make sure this passes; branch protection rules are not set yet.

**Review by Slesarew — APPROVED** [review]

**Comment by Slesarew** [comment]
Is this redundant with #18?

**Comment by Slesarew** [comment]
ok it is deprecated I suppose

**Pull request closed without merging**
